# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

def find_factors(n)
  number_of_factors = 0
  (1..Math.sqrt(n)).each do |x|
    if n % x == 0
      number_of_factors += 2
    elsif (x * x) == n
      number_of_factors -= 1
    end
  end
  number_of_factors
end

def find_triangle
  k = 0
  n = 0
  while find_factors(n) <= 500
    k += 1
    n = k * ((k + 1)/2 )
  end
  n
end
