// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  sumOfEvenFibNumbers = function(){
    var evenFibNumbers = [1,2];
    var evenFibNumbersSum = 0;
    while ((evenFibNumbers[evenFibNumbers.length - 2] + evenFibNumbers[evenFibNumbers.length - 1]) < 4000000){
      evenFibNumbers.push(evenFibNumbers[evenFibNumbers.length - 2] + evenFibNumbers[evenFibNumbers.length - 1])
    }
    evenFibNumbers.forEach(function(x){
      if(x % 2 === 0){
        evenFibNumbersSum += x; 
      }
    })
    return evenFibNumbersSum;
  };